### ISSUE TITLE
Invalid DSDT address if facp->x_dsdt is non-zero.

### ISSUE THREAD

**Issue by oberrow** [UltraOS/uACPI#42]
An invalid DSDT address if facp->x_dsdt is non-zero and the fadt table's length is less than 148
![image](https://github.com/UltraOS/uACPI/assets/72581470/6a95bf71-d692-4072-8b84-9c1b8f6f908f)
Offending lines: https://github.com/UltraOS/uACPI/blob/bf0bbff8c486f463d420691189a795ec398972b8/source/tables.c#L135-L139
Effect: An invalid physical address is passed to `uacpi_kernel_map`, causeing undefined behaviour, and an eventual page fault if the `uacpi_kernel_map` function is implemented incorrectly.
Environment:
x86_64 qemu, SeaBIOS.
Steps to reproduce:
1. Initialize uACPI, but the FACP's length is so that doesn't have fact->x_dsdt, and with another ACPI table after it, setting a breakpoint on  uacpi_kernel_map.
Eventually, you'll see that you get a garbage address in the `addr` parameter,

**Comment by oberrow** [comment]
As a workaround, if on qemu, use OVMF, which always uses 64-bit addresses for the ACPI tables, instead of SeaBIOS.

**Comment by 8infy** [comment]
Thanks for the report!

Yeah the FADT table needs very careful handling and a bunch of code to extract fields that are valid for a specific length. That code will have to be written before we can handle general purpose events anyway.
