### ISSUE TITLE
Modulo by 0 crashes

### ISSUE THREAD

**Issue by qookei** [UltraOS/uACPI#60]
ModOp is missing a guard like the one in DivOp, which causes the test runner to die with SIGFPE.

```asl
DefinitionBlock ("", "DSDT", 2, "uTEST", "TESTTABL", 0xF0F0F0F0)
{
    Method (_INI, 0, NotSerialized)
    {
        Local0 = 0

        Debug = 1 / Local0
        Debug = 1 % Local0
    }
}
```

On a semi-related note, the ACPI spec seems to imply these should be fatal, and not just evaluate to 0?

In 19.6.31 Divide:
> Divide-by-zero exceptions are fatal.

In 19.6.85 Mod:
>  If Divisor evaluates to zero, a fatal exception is generated.

**Comment by d-tatianin** [comment]
Thanks for the bug report!

> On a semi-related note, the ACPI spec seems to imply these should be fatal, and not just evaluate to 0?

Yeah, I think NT just crashes in this case so aborting seems like the way to go here.
