### ISSUE TITLE
Curious: Use the AML parser standalone to implement a DSL?

### ISSUE THREAD

**Issue by IngwiePhoenix** [UltraOS/uACPI#61]
Hello there!

Title really says it all; the AML syntax looks like something I could use for a project. So, could this parser be de-coupled and used standalone by chance? This is really just a spontaneous thought I had, but it's worth asking.

Thank you and kind regards,
Ingwie

**Comment by d-tatianin** [comment]
Hey!

Well, I am definitely a bit surprised to hear that you liked ASL syntax! It's certainly not the most carefully designed language and has a lot of unspecified implementation-defined behavior and various pitfalls.

That being said there's nothing preventing you from stripping stuff like event/table management, sleep code and various other ACPI-specific features and only leaving the namespace and the interpreter as a standalone thing. Removing all of the aforementioned code and instead making it run raw AML code outside of tables should take a few hours tops.

I would even say the test runner application used to run test cases already sort of works like a standalone interpreter, the only difference is it expects AML code to come with a table header.

Thanks!
